### ISSUE TITLE
跑infer.sh样例报错

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [mindspore-lab/minddiffusion#65]
![image](https://github.com/mindspore-lab/minddiffusion/assets/84905965/e313788b-a320-47bd-9cad-ec11bbec3c94)
跑样例报错
```
(ms) root@v4ae1f9ac727411f9a25ff403f1244d0-task0-0:/code/minddiffusion/vision/stablediffusionv2# bash scripts/infer.sh
workspace /code/minddiffusion/vision/stablediffusionv2
WORK DIR:/code/minddiffusion/vision/stablediffusionv2
Loading model from models/stablediffusionv2_512.ckpt
LatentDiffusion: Running in eps-prediction mode
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
param not load: (['first_stage_model.encoder.down.3.downsample.conv.weight', 'first_stage_model.encoder.down.3.downsample.conv.bias', 'first_stage_model.decoder.up.0.upsample.conv.weight', 'first_stage_model.decoder.up.0.upsample.conv.bias'], ['cond_stage_model.transformer.transformer_layer.resblocks.23.attn.attn.in_proj.bias', 'cond_stage_model.transformer.transformer_layer.resblocks.23.attn.attn.in_proj.weight', 'cond_stage_model.transformer.transformer_layer.resblocks.23.attn.attn.out_proj.bias', 'cond_stage_model.transformer.transformer_layer.resblocks.23.attn.attn.out_proj.weight', 'cond_stage_model.transformer.transformer_layer.resblocks.23.c_fc.bias', 'cond_stage_model.transformer.transformer_layer.resblocks.23.c_fc.weight', 'cond_stage_model.transformer.transformer_layer.resblocks.23.c_proj.bias', 'cond_stage_model.transformer.transformer_layer.resblocks.23.c_proj.weight', 'cond_stage_model.transformer.transformer_layer.resblocks.23.ln_1.beta', 'cond_stage_model.transformer.transformer_layer.resblocks.23.ln_1.gamma', 'cond_stage_model.transformer.transformer_layer.resblocks.23.ln_2.beta', 'cond_stage_model.transformer.transformer_layer.resblocks.23.ln_2.gamma'])
Data shape for PLMS sampling is (8, 4, 64, 64)
Running PLMS Sampling with 50 timesteps
Traceback (most recent call last):
  File "txt2img.py", line 294, in <module>
    main()
  File "txt2img.py", line 269, in main
    x_T=start_code
  File "/code/minddiffusion/vision/stablediffusionv2/ldm/models/diffusion/plms.py", line 120, in sample
    unconditional_conditioning=unconditional_conditioning,
  File "/code/minddiffusion/vision/stablediffusionv2/ldm/models/diffusion/plms.py", line 167, in plms_sampling
    old_eps=old_eps, t_next=ts_next)
  File "/code/minddiffusion/vision/stablediffusionv2/ldm/models/diffusion/plms.py", line 230, in p_sample_plms
    e_t = get_model_output(x, t)
  File "/code/minddiffusion/vision/stablediffusionv2/ldm/models/diffusion/plms.py", line 195, in get_model_output
    e_t_uncond, e_t = ops.split((self.model.apply_model(x_in, t_in, c_in)), 0, 2)
  File "/root/miniconda3/envs/ms/lib/python3.7/site-packages/mindspore/ops/function/array_func.py", line 5259, in split
    raise ValueError(f"For split, the value of 'split_size_or_sections' must be more than zero, "
ValueError: For split, the value of 'split_size_or_sections' must be more than zero, but got 0.
```
猜想可能是mindspore版本接口不适配了。mindspore用的是2.0rc1

**Comment by zhangjunyi1225054736** [comment]
2.0接口变了一些，要重新修改脚本的，暂时我们还没适配2.0版本。
